config/routes.rb
Rails.application.routes.draw do
 

  resources :students
  resources :courses
  resources :colleges
  resources :idcards
  root 'students#index'

end

app/models/college.rb
class College < ActiveRecord::Base
	validates :college_name, :address, :presence => true
	validates_numericality_of :college_code, :allow_blank => true

	has_many :students
end

app/models/course.rb
class Course < ActiveRecord::Base
	validates :course_name, :description, :presence => true
	validates_numericality_of :course_code, :allow_blank => true
end

app/models/idcard.rb
class Idcard < ActiveRecord::Base
	validates :name, :designation, :idcard_type, :presence => true
	 belongs_to :student
end

app/models/student.rb
class Student < ActiveRecord::Base
  validates :first_name, :presence => true
  validates_numericality_of :phone,:allow_blank => true
  validates :email, :presence => true,
    :length => {:minimum => 3, :maximum => 254},
    #    :uniqueness => true,
  :format => {:with => /\A^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$\z/i}

 has_one :idcard
 belongs_to :college,:foreign_key => 'college_id'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController
	def new
    @college = College.new
  end

  def index
    @colleges = College.all

  end

  def create
    @college = College.new(college_params)
    if @college.save
      redirect_to colleges_path
    else
      render :action => 'new'
    end
  end
  def edit
    @college = College.find(params[:id])
  end
  def update
    @college = College.find(params[:id])
    if @college.update_attributes(college_params)
       redirect_to college_path
    else
       render :action => 'edit'
    end
  end

  def show
    @college = College.find(params[:id])
  end

  def destroy
    @college = College.find(params[:id])
    if @college.delete
      redirect_to colleges_path
    end

  end

  private

  def college_params
    params.require(:college).permit(:college_name,:college_code,:address  )
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def new
    @course = Course.new
  end

  def index
    @courses = Course.all

  end

  def create
    @course = Course.new(course_params)
    if @course.save
      redirect_to courses_path
    else
      render :action => 'new'
    end
  end
  def edit
    @course = Course.find(params[:id])
  end
  def update
    @course = Course.find(params[:id])
    if @course.update_attributes(course_params)
       redirect_to course_path
    else
       render :action => 'edit'
    end
  end

  def show
    @course = Course.find(params[:id])
  end

  def destroy
    @course = Course.find(params[:id])
    if @course.delete
      redirect_to courses_path
    end

  end

  private

  def course_params
    params.require(:course).permit(:course_name,:course_code,:description  )
  end
end

app/controllers/idcards_controller.rb
class IdcardsController < ApplicationController
		def new
    @idcard = Idcard.new
  end

  def index
    @idcards = Idcard.all

  end

  def create
    @idcard = Idcard.new(idcard_params)
    if @idcard.save
      redirect_to idcards_path
    else
      render :action => 'new'
    end
  end
  def edit
    @idcard = Idcard.find(params[:id])
  end
  def update
    @idcard = Idcard.find(params[:id])
    if @idcard.update_attributes(idcard_params)
       redirect_to idcard_path
    else
       render :action => 'edit'
    end
  end

  def show
    @idcard = Idcard.find(params[:id])
  end

  def destroy
    @idcard = Idcard.find(params[:id])
    if @idcard.delete
      redirect_to idcards_path
    end

  end

  private

  def idcard_params
    params.require(:idcard).permit(:name,:designation,:idcard_type,:student_id  )
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  
  def index
  	@students = Student.all
  end
  
  def new
  	@student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
       redirect_to students_path
    else
       render :action => 'new'
    end
  end

  def edit
    @student = Student.find(params[:id])
  end
  def update
    @student = Student.find(params[:id])
    if @student.update_attributes(student_params)
       redirect_to student_path
    else
       render :action => 'edit'
    end
  end


  def show
  	@student = Student.find(params[:id])
  end

  def destroy
    @student = Student.find(params[:id])
    if @student.delete
       redirect_to students_path
    end
  end

  private

  def student_params
    params.require(:student).permit(:first_name,:last_name,:middle_name,:phone,:date_of_birth,:email,:address,:college_id  )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def validation_errors(message)
      if message.class.to_s == "Array"
      message = message.join(", ")
      end
     return !message.to_s.blank? ? raw("<div style='color: red;'>"+message.to_s+"</div>") : ""
    end
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/idcards_helper.rb
module IdcardsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/colleges/_collegeForm.html.erb
<table>
<%= form_for @college do |f| %>
<tr>
	<td>College Name:</td>
	<td><%= f.text_field :college_name %>
	 <%= validation_errors @college.errors['college_name'] %></td>
</tr>
<tr>
	<td>College Code:</td>
	<td><%= f.text_field :college_code %>
	<%= validation_errors @college.errors['college_code'] %></td>
</tr>
<tr>
	<td>Address:</td>
	<td><%= f.text_field :address %>
	<%= validation_errors @college.errors['address'] %></td>
</tr>

<tr>
	
	<td colspan='2'><%= f.submit %>&nbsp;&nbsp; <%= link_to 'Cancel',colleges_path %></td>
</tr>
 
<% end %>
</table>

app/views/colleges/edit.html.erb
<h2>Edit Colleges</h2>
<%= render 'collegeForm' %>

app/views/colleges/index.html.erb
<h2>College List</h2>
<%= link_to 'Create New College', new_college_path %>
<table width='100%' border='3%'>

    <th>College Name</th>
	<th>College Code</th>
	<th> Options</th>

	<% @colleges.each do |i| %>
	
	<tr>
      <td><%= i.college_name %></td>
      <td><%= i.college_code %></td>
      <td><%= link_to 'View Details',college_path(i.id) %> | 
        <%= link_to 'Edit Details',edit_college_path(i.id) %> |
      	<%= link_to 'Delete',college_path(i.id),  :data => { :method => :delete,:confirm => "Are you Sure to delete this Student?"}  %></td>
     </tr>

<%end%>

</table>

app/views/colleges/new.html.erb
<h2>Create New Colleges</h2>
<%= render 'collegeForm' %>

app/views/colleges/show.html.erb
<h2>View College Details</h2>
<table>

<tr>
	<td>Colleges Name:</td>
	<td><%= @college.college_name %></td>
</tr>
<tr>
	<td>College Code:</td>
	<td><%= @college.college_code %></td>
</tr>
<tr>
	<td>Address:</td>
	<td><%= @college.address %></td>
</tr>
<tr>
	<td>Students:</td>
	<td><%= @college.students.count %></td>
</tr>
<table width='100%' border='3%'>

    <th>First Name</th>
	<th>Last Name</th>
	<th> Options</th>
	<% if @college.students.empty? %>
	<tr>
		<td> No students found </td>
	</tr>
	<% else %>


	<% @college.students.each do |i| %>
	
	<tr>
      <td><%= i.first_name %></td>
      <td><%= i.last_name %></td>
      <td><%= link_to 'view details',student_path(i.id) %> | 
          <%= link_to 'Edit Student',edit_student_path(i.id) %> |
      	  <%= link_to 'Delete',student_path(i.id),  :data => { :method => :delete,:confirm => "Are you Sure to delete this Student?"}  %></td>
     </tr>
<%end%>
<%end%>

</table>

</table>
<%= link_to 'back',colleges_path %>

app/views/courses/_courseForm.html.erb
<table>
<%= form_for @course do |f| %>
<tr>
	<td>Course Name:</td>
	<td><%= f.text_field :course_name %>
	 <%= validation_errors @course.errors['course_name'] %></td>
</tr>
<tr>
	<td>Course Code:</td>
	<td><%= f.text_field :course_code %>
	<%= validation_errors @course.errors['course_code'] %></td>
</tr>
<tr>
	<td>Description:</td>
	<td><%= f.text_field :description %>
	<%= validation_errors @course.errors['description'] %></td>
</tr>

<tr>
	
	<td colspan='2'><%= f.submit %>&nbsp;&nbsp; <%= link_to 'Cancel',courses_path %></td>
</tr>
 
<% end %>
</table>

app/views/courses/edit.html.erb
<h2>Edit Course</h2>
<%= render 'courseForm' %>

app/views/courses/index.html.erb
<h2>Courses List</h2>
<%= link_to 'Create New Course', new_course_path %>
<table width='100%' border='3%'>

    <th>Course Name</th>
	<th>Course Code</th>
	<th> Options</th>

	<% @courses.each do |i| %>
	
	<tr>
      <td><%= i.course_name %></td>
      <td><%= i.course_code %></td>
      <td><%= link_to 'View Details',course_path(i.id) %> | 
        <%= link_to 'Edit Details',edit_course_path(i.id) %> |
      	<%= link_to 'Delete',course_path(i.id),  :data => { :method => :delete,:confirm => "Are you Sure to delete this Student?"}  %></td>
     </tr>

<%end%>

</table>

app/views/courses/new.html.erb
<h2>Create New Course</h2>
<%= render 'courseForm' %>

app/views/courses/show.html.erb
<h2>View Course Details</h2>
<table>

<tr>
	<td>Course Name:</td>
	<td><%= @course.course_name %></td>
</tr>
<tr>
	<td>Course Code:</td>
	<td><%= @course.course_code %></td>
</tr>
<tr>
	<td>Description:</td>
	<td><%= @course.description %></td>
</tr>

</table>
<%= link_to 'back',courses_path %>

app/views/idcards/_idcardForm.html.erb
<table>
<%= form_for @idcard do |f| %>
<tr>
	<td>Idcard Name:</td>
	<td><%= f.text_field :name %>
	 <%= validation_errors @idcard.errors['name'] %></td>
</tr>
<tr>
	<td>Designation:</td>
	<td><%= f.text_field :designation %>
	<%= validation_errors @idcard.errors['designation'] %></td>
</tr>
<tr>
	<td>Card Type:</td>
	<td><%= f.text_field :idcard_type %>
	<%= validation_errors @idcard.errors['idcard_type'] %></td>
</tr>
<tr>
	<td>Student id:</td>
	<% @students = Student.all %>
	<td> <%= f.select :student_id, options_for_select(@students.collect {|p| [ p['first_name'], p['id']] }) %></td>
</tr>


<tr>
	
	<td colspan='2'><%= f.submit %>&nbsp;&nbsp; <%= link_to 'Cancel',idcards_path %></td>
</tr>
 
<% end %>
</table>

app/views/idcards/edit.html.erb
<h2>Edit Idcard details</h2>
<%= render 'idcardForm' %>

app/views/idcards/index.html.erb
<h2>Idcards List</h2>
<%= link_to 'Create New Idcard', new_idcard_path %>
<table width='100%' border='3%'>

    <th>Employee Name</th>
	<th>Designation</th>
	<th> Options</th>

	<% @idcards.each do |i| %>
	
	<tr>
      <td><%= i.name %></td>
      <td><%= i.designation %></td>
      <td><%= link_to 'View Details',idcard_path(i.id) %> | 
        <%= link_to 'Edit Details',edit_idcard_path(i.id) %> |
      	<%= link_to 'Delete',idcard_path(i.id),  :data => { :method => :delete,:confirm => "Are you Sure to delete this Student?"}  %></td>
     </tr>

<%end%>

</table>

app/views/idcards/new.html.erb
<h2>Create New Idcard</h2>
<%= render 'idcardForm' %>

app/views/idcards/show.html.erb
<h2>View Idcard Details</h2>
<table>

<tr>
	<td>Idcard Name:</td>
	<td><%= @idcard.name %></td>
</tr>
<tr>
	<td>Designation:</td>
	<td><%= @idcard.designation %></td>
</tr>
<tr>
	<td>Idcard Type:</td>
	<td><%= @idcard.idcard_type %></td>
</tr>

<tr>
	<td>Student name:</td>

	<td><%= @idcard.student.first_name unless @idcard.student_id.nil? %></td>
</tr>

</table>
<%= link_to 'back',idcards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BalaTestApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to 'Idcards',idcards_path unless params[:controller] == 'idcards'%>
<%= link_to 'Colleges',colleges_path unless params[:controller] == 'colleges'%>
<%= link_to 'Students',root_path unless params[:controller] == 'students'  %>
<%= link_to 'Courses',courses_path unless params[:controller] == 'courses'%>

<%= yield %>

</body>
</html>

app/views/students/_studentForm.html.erb
<table>
<%= form_for @student do |f| %>
<tr>
	<td>First Name:</td>
	<td><%= f.text_field :first_name %>
	 <%= validation_errors @student.errors['first_name'] %></td>
</tr>
<tr>
	<td>Middle Name:</td>
	<td><%= f.text_field :middle_name %></td>
</tr>
<tr>
	<td>Last Name:</td>
	<td><%= f.text_field :last_name %></td>
</tr>
<tr>
	<td>Phone:</td>
	<td><%= f.text_field :phone %>
		<%= validation_errors @student.errors['phone'] %></td>
</tr>
<tr>
	<td>Date of Birth:</td>
	<td><%= f.text_field :date_of_birth %></td>
</tr>
<tr>
	<td>Email:</td>
	<td><%= f.text_field :email %>
		<%= validation_errors @student.errors['email'] %></td>
</tr>
<tr>
	<td>Address:</td>
	<td><%= f.text_area :address %></td>
</tr>
<tr>

	<tr>
	<td>College:</td>
	<% @colleges = College.all %>
	<td> <%= f.select :college_id, options_for_select(@colleges.collect {|p| [ p['college_name'], p['id']] }) %></td>
</tr>
	
	<td colspan='2'><%= f.submit %>&nbsp;&nbsp; <%= link_to 'Cancel',students_path %></td>
</tr>
 
<% end %>
</table>

app/views/students/edit.html.erb
<h2>Edit Student</h2>
<%= render 'studentForm' %>

app/views/students/index.html.erb
<h2>Student List</h2>
<%= link_to 'Create New Student', new_student_path %>
<table width='100%' border='3%'>

    <th>First Name</th>
	<th>Last Name</th>
	<th> Options</th>

	<% @students.each do |i| %>
	
	<tr>
      <td><%= i.first_name %></td>
      <td><%= i.last_name %></td>
      <td><%= link_to 'view details',student_path(i.id) %> | 
          <%= link_to 'Edit Student',edit_student_path(i.id) %> |
      	  <%= link_to 'Delete',student_path(i.id),  :data => { :method => :delete,:confirm => "Are you Sure to delete this Student?"}  %></td>
     </tr>

<%end%>

</table>

app/views/students/new.html.erb
<h2>Create New Student</h2>
<%= render 'studentForm' %>

app/views/students/show.html.erb
<h2>View Student Details</h2>
<table>

<tr>
	<td>First Name:</td>
	<td><%= @student.first_name %></td>
</tr>
<tr>
	<td>Middle Name:</td>
	<td><%= @student.middle_name %></td>
</tr>
<tr>
	<td>Last Name:</td>
	<td><%= @student.last_name %></td>
</tr>
<tr>
	<td>Phone:</td>
	<td><%= @student.phone %></td>
</tr>
<tr>
	<td>Date of Birth:</td>
	<td><%= @student.date_of_birth %></td>
</tr>
<tr>
	<td>Email:</td>
	<td><%= @student.email %></td>
</tr>
<tr>
	<td>Address:</td>
	<td><%= @student.address %></td>
</tr>
<tr>
	<td>College:</td>

	<td><%= @student.college.college_name %></td>
</tr>


</table>
<%= link_to 'back',students_path %>